"Games are where the kids are" section
fielddaylab/fielddaysite pull request #45
Opened 2024-08-30 18:53 UTC by jwisc

2024-09-09 19:30 UTC, rwilkinson3 requested changes

2024-09-09 19:30 UTC, rwilkinson3 commented on assets/scss/_home.scss
> +        max-height: 643px;
At the "Desktop - Huge" size the Figma mockup shows the cabin image extending vertically to the `<div class="bottom-frame"></div>` separator at the bottom of the level. I think this `max-height` is causing a gap, as the image doesn't reach the separator.

2024-09-09 19:30 UTC, rwilkinson3 commented on redesign.php
> +    </section>
Should add the `<div class="bottom-frame"></div>` separator between these levels.

2024-09-10 20:38 UTC, rwilkinson3 requested changes
I'm still seeing a gap between the cabin and bottom-frame divs as the cabin bobs up and down.
![gap](https://github.com/user-attachments/assets/dee995c3-2241-4e33-8dd7-e9425bee0195)

Should add the `<div class="bottom-frame"></div>` separator between the helm and cabin levels.
![bottom-frame](https://github.com/user-attachments/assets/f0d87b35-31f9-46c0-909b-9cfaede291f4)

2024-09-12 18:49 UTC, msherry2 approved these changes
Thanks!

2024-09-12 18:57 UTC, merged